# Generated by Django 4.0.5 on 2022-06-23 11:24

from django.db import migrations, models
import django.db.models.deletion

# Migration : 기존에 있던 프로젝트의 DB모델에 application의 데이터 모델을 이식시키는 과정
# python mysite/manage.py makemigrations (앱 이름) <- 애플리케이션에서 모델의 수정 사항 기록
# python mysite/manage.py migrate <- 실제 migration


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_data', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
