# 모든 레코드 조회하기
SELECT * FROM ANIMAL_INS

# 역순 정렬하기
SELECT NAME, DATETIME FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC
# 아픈 동물 찾기

SELECT ANIMAL_ID, NAME FROM ANIMAL_INS
WHERE INTAKE_CONDITION = "Sick"

# 어린 동물 찾기
SELECT animal_id, name FROM ANIMAL_INS
where not intake_condition = "Aged"

# 동물의 아이디와 이름
SELECT animal_id, name FROM ANIMAL_INS
order by animal_id

# 여러 기준으로 정렬하기
SELECT animal_id, name, datetime FROM ANIMAL_INS
order by name, datetime desc

# 상위 n개 레코드
SELECT name FROM ANIMAL_INS
where datetime = (select min(datetime) FROM ANIMAL_INS)

# 흉부외과 또는 일반외과 의사 목록 출력하기 (난이도 1)
SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD,'%Y-%m-%d') AS HIRE_YMD
FROM DOCTOR
WHERE MCDP_CD = 'CS' OR MCDP_CD = 'GS'
ORDER BY HIRE_YMD DESC, DR_NAME ASC

# 3월에 태어난 여성 회원 목록 출력하기 (난이도 2)
SELECT MEMBER_ID, MEMBER_NAME, GENDER, 
    DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d')AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER='W' AND DATE_OF_BIRTH LIKE '%-03-%' AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC

# 강원도에 있는 생산 공장 목록 출력하기 (난이도 1)
SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
FROM FOOD_FACTORY
WHERE ADDRESS LIKE '강원도%'
ORDER BY FACTORY_ID ASC

# 서울에 위치한 식당 목록 출력하기 (난이도 4)
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, 
    A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO A JOIN REST_REVIEW B 
ON A.REST_ID = B.REST_ID
WHERE A.ADDRESS LIKE '서울%'
GROUP BY A.REST_ID
ORDER BY SCORE DESC, A.FAVORITES DESC

# 과일로 만든 아이스크림 고르기 (난이도 1)
SELECT A.FLAVOR
FROM  FIRST_HALF A JOIN ICECREAM_INFO B
ON A.FLAVOR = B.FLAVOR
WHERE A.TOTAL_ORDER>3000 and B.INGREDIENT_TYPE = 'fruit_based'
ORDER BY A.TOTAL_ORDER DESC

# 12세 이하인 여자 환자 목록 출력하기 (난이도 1)
SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO, 'NONE') AS TLNO
FROM PATIENT
WHERE AGE<=12 AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME ASC

# 오프라인/온라인 판매 데이터 통합하기 (난이도 4)
SELECT DATE_FORMAT(A.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, A.PRODUCT_ID, A.USER_ID, A.SALES_AMOUNT
FROM (
    SELECT ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE FROM ONLINE_SALE
    UNION ALL
    SELECT OFFLINE_SALE_ID, NULL, PRODUCT_ID, SALES_AMOUNT, SALES_DATE FROM OFFLINE_SALE
) A
WHERE A.SALES_DATE LIKE '2022-03%'
ORDER BY A.SALES_DATE, A.PRODUCT_ID, A.USER_ID